CREATE TABLE songs(
   position                  INTEGER  NOT NULL PRIMARY KEY 
  ,title                     VARCHAR(60) NOT NULL
  ,artist                    VARCHAR(60) NOT NULL
  ,label                     VARCHAR(8) NOT NULL
  ,lastWeek                  VARCHAR(3) NOT NULL
  ,timeSpent                 INTEGER  NOT NULL
  ,highestPosition           INTEGER  NOT NULL
);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (1,'I Don''t Care','Ed Sheeran & Justin Bieber','WMA/UMA','1',3,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (2,'Sucker','Jonas Brothers','REP/UMA','2',13,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (3,'ME!','Taylor Swift ft. Brendon Urie','REP/UMA','4',5,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (4,'If I Can''t Have You','Shawn Mendes','ISL/UMA','3',4,3);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (5,'Can We Pretend','Pink ft. Cash Cash','RCA/SME','29',2,5);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (6,'Someone You Loved','Lewis Capaldi','UMA','6',11,6);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (7,'Don''t Call Me Up','Mabel','POL/UMA','9',12,7);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (8,'bad guy','Billie Eilish','IGA/UMA','5',9,4);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (9,'Dancing With A Stranger','Sam Smith & Normani','CAP/EMI','7',20,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (10,'Woke Up Late','Drax Project ft. Hailee Steinfeld','UMA','18',12,10);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (11,'Talk','Khalid','RCA/SME','8',16,8);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (12,'Cross Me','Ed Sheeran ft. Chance The Rapper & PnB Rock','ATL/WMA','NEW',1,12);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (13,'Old Town Road (Remix)','Lil Nas X ft. Billy Ray Cyrus','COL/SME','11',8,11);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (14,'SOS','Avicii ft. Aloe Blacc','IGA/UMA','12',7,5);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (15,'So Am I','Ava Max','ATL/WMA','14',12,3);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (16,'Who Do You Love','The Chainsmokers ft. 5 Seconds Of Summer','COL/SME','13',16,4);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (17,'Nightmare','Halsey','CAP/EMI','45',2,17);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (18,'Good Lord','Birds Of Tokyo','EMI','17',13,5);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (19,'Here With Me','Marshmello ft. CHVRCHES','REP/UMA','22',11,7);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (20,'3 Nights','Dominic Fike','COL/SME','15',20,4);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (21,'i''m so tired...','Lauv & Troye Sivan','EMI/IND','16',17,13);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (22,'Walk Me Home','Pink','RCA/SME','10',14,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (23,'Easier','5 Seconds Of Summer','EMI','NEW',1,23);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (24,'Body','Loud Luxury ft. brando','UMA','20',37,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (25,'Nothing Breaks Like A Heart','Mark Ronson ft. Miley Cyrus','RCA/SME','19',21,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (26,'Bad Liar','Imagine Dragons','IGA/UMA','23',22,4);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (27,'Then What','Illy','SME','NEW',1,27);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (28,'Piece Of Your Heart','Meduza ft. Goodboys','NEON/UMA','30',4,28);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (29,'Love Someone','Lukas Graham','WB/WMA','26',30,4);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (30,'Exit Sign','Hilltop Hoods ft. Illy & Ecca Vandal','HTH/UMA','31',14,21);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (31,'Sunflower','Post Malone & Swae Lee','REP/UMA','25',27,15);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (32,'Young Again','Morgan Evans','WMA','47',3,32);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (33,'Joy','Bastille','VIR/EMI','21',3,21);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (34,'7 Minutes','Dean Lewis','ISL/UMA','33',19,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (35,'Paradise','Bazzi','ATL/WMA','50',7,35);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (36,'Sweet But Psycho','Ava Max','ATL/WMA','37',23,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (37,'Stay Awake','Dean Lewis','ISL/UMA','28',10,11);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (38,'Painkiller','Ruel','RCA/SME','44',4,38);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (39,'Summer Days','Martin Garrix ft. Macklemore & Patrick Stump','EPIC/SME','35',4,35);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (40,'Mess Her Up','Amy Shark','WL/SME','24',13,7);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (41,'Waiting','KIAN','EMI','38',27,10);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (42,'Girls Like You','Maroon 5 ft. Cardi B','IGA/UMA','34',47,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (43,'Promises','Calvin Harris & Sam Smith ft. Jessie Reyez','EMI/SME','36',36,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (44,'Hold My Girl','George Ezra','COL/SME','55',18,10);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (45,'Without Me','Halsey','CAP/EMI','41',28,9);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (46,'Sunday','Jessica Mauboy','SME','32',7,30);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (47,'Don''t Feel Like Crying','Sigrid','ISL/UMA','46',3,46);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (48,'Happier','Marshmello & Bastille','AST/EMI','40',35,3);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (49,'You Say','Lauren Daigle','ADA/WMA','58',19,16);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (50,'Johnny Run Away','Tones And I','IND/SME','27',12,27);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (51,'Hurt Somebody','Noah Kahan & Julia Michaels','REP/UMA','53',64,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (52,'High Hopes','Panic! At The Disco','FBR/WMA','49',47,4);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (53,'Youngblood','5 Seconds Of Summer','CAP/EMI','42',53,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (54,'Truth Hurts','Lizzo','ATL/WMA','64',3,54);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (55,'Blame It On Your Love','Charli XCX ft. Lizzo','ATL/WMA','NEW',1,55);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (56,'What I Like About You','Jonas Blue ft. Theresa Rex','VIR/EMI','R/E',7,41);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (57,'Close To Me','Ellie Goulding & Diplo ft. Swae Lee','POL/UMA','52',21,8);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (58,'Rewrite The Stars','Anne-Marie & James Arthur','ATL/WMA','77',17,19);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (59,'Shotgun','George Ezra','COL/SME','59',44,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (60,'No Tears Left To Cry','Ariana Grande','REP/UMA','98',51,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (61,'Stay','Zedd & Alessia Cara','IGA/UMA','51',64,3);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (62,'Solid Gold','PNAU ft. Kira Divine & Marques Toliver','IND','54',3,54);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (63,'thank u, next','Ariana Grande','REP/UMA','48',25,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (64,'A Million Dreams','Pink','ATL/WMA','62',25,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (65,'break up with your girlfriend, i�m bored','Ariana Grande','REP/UMA','39',16,19);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (66,'Remind Me To Forget','Kygo ft. Miguel','SME','68',55,5);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (67,'IDGAF','Dua Lipa','WB/WMA','66',48,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (68,'Mama','Jonas Blue ft. William Singe','VIR/EMI','69',83,5);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (69,'Shallow','Lady Gaga & Bradley Cooper','IGA/UMA','72',29,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (70,'Can''t Stop The Feeling!','Justin Timberlake','RCA/SME','63',134,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (71,'What Lovers Do','Maroon 5 ft. SZA','A&M/UMA','94',73,10);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (72,'Think Of Me','The Veronicas','SME','43',9,7);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (73,'Dance Monkey','Tones And I','IND/SME','NEW',1,73);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (74,'Wake Me Up','Avicii','UNI/UMA','74',159,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (75,'Power Is Power','SZA, The Weeknd & Travis Scott','SME','61',4,50);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (76,'LIFE','Conrad Sewell','SME','NEW',1,76);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (77,'1999','Charli XCX & Troye Sivan','ATL/WMA','57',28,16);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (78,'Day Drunk','Morgan Evans','WMA','70',37,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (79,'Let You Love Me','Rita Ora','ATL/WMA','71',30,4);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (80,'Earth','Lil Dicky','BMG','R/E',3,80);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (81,'There''s Nothing Holdin'' Me Back','Shawn Mendes','ISL/UMA','89',101,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (82,'Cheap Thrills','Sia','INERTIA','79',122,6);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (83,'The Middle','Zedd, Maren Morris & Grey','IGA/UMA','83',64,3);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (84,'Vossi Bop','Stormzy','ATL/WMA','97',3,84);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (85,'Locked Out Of Heaven','Bruno Mars','ATL/WMA','R/E',97,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (86,'Before I Go','Guy Sebastian','SME','78',25,6);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (87,'Gimme','BANKS','EMI','R/E',2,87);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (88,'Nowhere To Go','Hayden James & NAATIONS','FC','93',3,88);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (89,'Cheerleader','OMI','SME','92',62,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (90,'Undrunk','FLETCHER','CAP/EMI','67',2,67);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (91,'Shutting Down Our Town','Jimmy Barnes','MUSHROOM','NEW',1,91);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (92,'Elastic Heart','Sia','INERTIA','R/E',51,2);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (93,'You Little Beauty','FISHER','IND','88',2,88);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (94,'Carry On','Kygo & Rita Ora','RCA/SME','56',3,56);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (95,'Feel It Still','Portugal. The Man','ATL/WMA','R/E',77,5);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (96,'Better In Blak','Thelma Plum','WMA','96',4,87);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (97,'Only Girl (In The World)','Rihanna','IDJ/UMA','R/E',44,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (98,'These Days','Rudimental ft. Jess Glynne, Macklemore & Dan Caplen','WMA','80',66,1);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (99,'Jubel','Klingande','NEON/UMA','R/E',45,4);
INSERT INTO songs(position,title,artist,label,lastWeek,timeSpent,highestPosition) VALUES (100,'Uptown Funk','Mark Ronson ft. Bruno Mars','RCA/SME','84',171,1);
